artifacts_root: artifacts

yolo8:
  model_name: yolov8n.pt
  model_type: pretrained_models
  model_parent_folder: ${artifacts_root}/${yolo8.model_type}
  model_saved_path: ${yolo8.model_parent_folder}/${yolo8.model_name}

trained_yolo8_model:
  model_name: best.pt
  model_type: trained_yolo8_model
  model_parent_folder: ${artifacts_root}/${trained_yolo8_model.model_type}/weights
  model_saved_path: ${trained_yolo8_model.model_parent_folder}/${trained_yolo8_model.model_name}

inference_yolo8_model:
  model_path : ${trained_yolo8_model.model_saved_path}